var Globals = {
	deltaTime: 0.0,
	fps: 0.0,
	acceleration: 3,
	velocityEpsilon: 0.1,
	colorChangeFrequency: 4,
	cycleNum: 0,
	background: "#000000",
	blocked: true,
	context: null,
	height: 0,
	width: 0,
	precision: 4,
	square: new Square(),
	keys: new Keys(),
	scores: new Scores(),
	_defaults: {
		deltaTime: 0.0,
		fps: 0.0,
		acceleration: 3,
		velocityEpsilon: 0.1,
		colorChangeFrequency: 4,
		cycleNum: 0,
		background: "#000000",
		blocked: true,
		context: null,
		height: 0,
		width: 0,
		precision: 4,
		square: new Square(),
		keys: new Keys(),
		scores: new Scores()
	}
}